org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
org.gradle.workers.max=4
android.enableJetifier=true
org.gradle.daemon=true
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Disable Kotlin incremental compilation to fix cross-drive path issue (C: vs D:)
kotlin.incremental=false
