// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO0xXunQbdVUkHBLDzkMosbz8WW8W6PZk',
    appId: '1:821042028276:web:c8b1b19333f583dbd0c8a1',
    messagingSenderId: '821042028276',
    projectId: 'organisync-bdca5',
    authDomain: 'organisync-bdca5.firebaseapp.com',
    storageBucket: 'organisync-bdca5.firebasestorage.app',
    measurementId: 'G-ERE9Y49L4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRBh43rW5LLE09WFpcoEDOVXhfgoGMQjc',
    appId: '1:821042028276:android:369135003c050f71d0c8a1',
    messagingSenderId: '821042028276',
    projectId: 'organisync-bdca5',
    storageBucket: 'organisync-bdca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRcwOl_9A6qdFrN8s509TYNO_scenCmtw',
    appId: '1:821042028276:ios:e4e00f05c9630c4cd0c8a1',
    messagingSenderId: '821042028276',
    projectId: 'organisync-bdca5',
    storageBucket: 'organisync-bdca5.firebasestorage.app',
    iosBundleId: 'com.example.organisync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRcwOl_9A6qdFrN8s509TYNO_scenCmtw',
    appId: '1:821042028276:ios:e4e00f05c9630c4cd0c8a1',
    messagingSenderId: '821042028276',
    projectId: 'organisync-bdca5',
    storageBucket: 'organisync-bdca5.firebasestorage.app',
    iosBundleId: 'com.example.organisync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO0xXunQbdVUkHBLDzkMosbz8WW8W6PZk',
    appId: '1:821042028276:web:be2aa37c61156fb4d0c8a1',
    messagingSenderId: '821042028276',
    projectId: 'organisync-bdca5',
    authDomain: 'organisync-bdca5.firebaseapp.com',
    storageBucket: 'organisync-bdca5.firebasestorage.app',
    measurementId: 'G-5LMS7YXW1B',
  );
}
